[colors.primary]
background = "#000000"

[font]
size = 12.0

[font.bold]
family = "LiterationMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "LiterationMono Nerd Font"
style = "Light Italic"

[font.italic]
family = "LiterationMono Nerd Font"
style = "Extra Light Italic"

[font.normal]
family = "LiterationMono Nerd Font"
style = "Light"

[window]
dynamic_title = true

[window.padding]
x = 5
y = 5
